global_frame: wcias_odom
rolling_window: true

# footprint: [[-0.63, -0.30], [-0.63, 0.30], [0.73,0.30], [0.73, -0.30]] #[[-0.30, -0.63], [-0.30, 0.63], [0.30,0.63], [0.30, -0.63]] # if the robot is not circular
footprint_padding: 0.01

robot_base_frame: wcias_base_footprint #base_link in husky tutorial
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

width: 10.0
height: 10.0

resolution: 0.05 #0.02 in marrtino tutorial

obstacle_range: 5.5 #2.5 in marrtino tutorial
raytrace_range: 6.0 #3.0 in marrtino tutorial

plugins:
  - {name: static_layer_c, type: "costmap_2d::StaticLayer"}

#layer definitions
static_layer_c:
  map_topic: "/move_base_mpc/local_costmap/costmap"
  subscribe_to_updates: true
  observation_persistence: 1.0

