global_frame: wcias_odom
rolling_window: true
track_unknown_space: true

plugins:
  - {name: laser_layer_temp, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}
  - {name: half_layer,           type: "half_layer::HalfLayer"}
  #- {name: obstacle_layer,   type: "costmap_2d::ObstacleLayer"}
  #  - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
