ProximityPlanner:
    frame_id: "wcias_base_link"
    angle_min: -3.141592653589793
    angle_max: 3.141592653589793
    angle_inc: 0.17453293005625406
    range_min: 0
    range_max: 4.1
    min_cost: 250
    repellor_angular_strength: 0.1
    repellor_angular_decay: 0.1
    vel_linear_min: 0
    vel_linear_max: 0.2
    vel_angular_min: 0
    vel_angular_max: 0.2
    rel_verts_x: [ 0.65,-0.50,-0.50, 0.65, 0.0 ]
    rel_verts_y: [ 0.35, 0.35,-0.35,-0.35, 0.0 ]
    safe_distance: 0.3
    arrival_radius: 0.5
